### ISSUE TITLE
S3I12 -- Implement Follow

### ISSUE THREAD

**Issue by mcartervt** [kachalmers/software-engineering-react-s2-team1-project#9]
Building "Follow" in the front end

**Comment by kachalmers** [comment]
Follow button implemented as part of pull request https://github.com/kachalmers/software-engineering-react-s2-team1-project/pull/12 . Pull request currently under review.

**Comment by mnolan34** [comment]
Can this be marked as closed? @kachalmers @mcartervt

**Comment by kachalmers** [comment]
> Can this be marked as closed? @kachalmers @mcartervt

Yes; closing now.
